# Generated by Django 2.2 on 2021-01-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_teachinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinghour',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
