# Generated by Django 2.2 on 2021-01-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_teachinghour_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinghour',
            name='ttype',
            field=models.CharField(choices=[('Course', 'Course'), ('Laboratory', 'Laboratory'), ('Seminary', 'Seminary'), ('Activity', 'Activity')], default='Course', max_length=20, null=True),
        ),
    ]
