# Generated by Django 2.2 on 2021-01-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='subject',
            field=models.ManyToManyField(to='database.Subject'),
        ),
    ]
