# Generated by Django 2.2 on 2021-01-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210124_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagestream',
            name='abrv',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
